-- MySQL Script generated by MySQL Workbench
-- Sun Jan 24 17:37:01 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pappherDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pappherDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pappherDB` DEFAULT CHARACTER SET utf8 ;
USE `pappherDB` ;

-- -----------------------------------------------------
-- Table `pappherDB`.`paper_master`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pappherDB`.`paper_master` (
  `paper_id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `abstract` TEXT NOT NULL,
  `chapchar_link` VARCHAR(45) NOT NULL,
  `publish_month` CHAR(7) NOT NULL,
  `ins_date` TIMESTAMP NULL,
  `upd_date` TIMESTAMP NULL,
  `del_date` TIMESTAMP NULL,
  `del_flg` CHAR(1) NOT NULL,
  PRIMARY KEY (`paper_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pappherDB`.`author_master`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pappherDB`.`author_master` (
  `author_id` INT NOT NULL,
  `author_name` VARCHAR(45) NOT NULL,
  `ins_date` TIMESTAMP NULL,
  `upd_date` TIMESTAMP NULL,
  `del_date` TIMESTAMP NULL,
  `del_flg` CHAR(1) NOT NULL,
  PRIMARY KEY (`author_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pappherDB`.`keyword_master`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pappherDB`.`keyword_master` (
  `kwd_id` INT NOT NULL,
  `kwd_name` VARCHAR(45) NOT NULL,
  `ins_date` TIMESTAMP NULL,
  `upd_date` TIMESTAMP NULL,
  `del_date` TIMESTAMP NULL,
  `del_flg` CHAR(1) NOT NULL,
  PRIMARY KEY (`kwd_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pappherDB`.`paper_author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pappherDB`.`paper_author` (
  `paper_author_id` INT NOT NULL,
  `paper_id` INT NOT NULL,
  `author_id` INT NOT NULL,
  `ins_date` TIMESTAMP NULL,
  `upd_date` TIMESTAMP NULL,
  `del_date` TIMESTAMP NULL,
  `del_flg` CHAR(1) NOT NULL,
  INDEX `fk_paper_author_author1_idx` (`author_id` ASC),
  PRIMARY KEY (`paper_author_id`),
  CONSTRAINT `fk_paper_author_paper`
    FOREIGN KEY (`paper_id`)
    REFERENCES `pappherDB`.`paper_master` (`paper_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paper_author_author1`
    FOREIGN KEY (`author_id`)
    REFERENCES `pappherDB`.`author_master` (`author_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pappherDB`.`paper_keyword`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pappherDB`.`paper_keyword` (
  `paper_kwd_id` INT NOT NULL,
  `paper_id` INT NOT NULL,
  `kwd_id` INT NOT NULL,
  `ins_date` TIMESTAMP NULL,
  `upd_date` TIMESTAMP NULL,
  `del_date` TIMESTAMP NULL,
  `del_flg` CHAR(1) NOT NULL,
  INDEX `fk_paper_keyword_paper1_idx` (`paper_id` ASC),
  INDEX `fk_paper_keyword_keyword1_idx` (`kwd_id` ASC),
  PRIMARY KEY (`paper_kwd_id`),
  CONSTRAINT `fk_paper_keyword_paper1`
    FOREIGN KEY (`paper_id`)
    REFERENCES `pappherDB`.`paper_master` (`paper_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paper_keyword_keyword1`
    FOREIGN KEY (`kwd_id`)
    REFERENCES `pappherDB`.`keyword_master` (`kwd_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pappherDB`.`paper_reference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pappherDB`.`paper_reference` (
  `paper_reference_id` INT NOT NULL,
  `src_paper_id` INT NOT NULL,
  `dst_paper_id` INT NOT NULL,
  `ins_date` TIMESTAMP NULL,
  `upd_date` TIMESTAMP NULL,
  `del_date` TIMESTAMP NULL,
  `del_flg` CHAR(1) NOT NULL,
  INDEX `fk_paper_reference_paper_master1_idx` (`src_paper_id` ASC),
  INDEX `fk_paper_reference_paper_master2_idx` (`dst_paper_id` ASC),
  PRIMARY KEY (`paper_reference_id`),
  CONSTRAINT `fk_paper_reference_paper_master1`
    FOREIGN KEY (`src_paper_id`)
    REFERENCES `pappherDB`.`paper_master` (`paper_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paper_reference_paper_master2`
    FOREIGN KEY (`dst_paper_id`)
    REFERENCES `pappherDB`.`paper_master` (`paper_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pappherDB`.`source_master`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pappherDB`.`source_master` (
  `src_id` INT NOT NULL,
  `src_name` VARCHAR(45) NOT NULL,
  `priority_number` CHAR(1) NOT NULL,
  `ins_date` TIMESTAMP NULL,
  `upd_date` TIMESTAMP NULL,
  `del_date` TIMESTAMP NULL,
  `del_flg` CHAR(1) NOT NULL,
  PRIMARY KEY (`src_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pappherDB`.`paper_souce_url`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pappherDB`.`paper_souce_url` (
  `paper_souce_url` INT NOT NULL,
  `paper_id` INT NOT NULL,
  `src_id` INT NOT NULL,
  `paper_src_url` VARCHAR(255) NOT NULL,
  `ins_date` TIMESTAMP NULL,
  `upd_date` TIMESTAMP NULL,
  `del_date` TIMESTAMP NULL,
  `del_flg` CHAR(1) NOT NULL,
  PRIMARY KEY (`paper_souce_url`),
  INDEX `fk_paper_souce_url_paper_master1_idx` (`paper_id` ASC),
  INDEX `fk_paper_souce_url_keyword_master_copy11_idx` (`src_id` ASC),
  CONSTRAINT `fk_paper_souce_url_paper_master1`
    FOREIGN KEY (`paper_id`)
    REFERENCES `pappherDB`.`paper_master` (`paper_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paper_souce_url_keyword_master_copy11`
    FOREIGN KEY (`src_id`)
    REFERENCES `pappherDB`.`source_master` (`src_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
